# Generated by Django 4.2.4 on 2023-08-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("typeahead_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
